package modelo;
// Generated 10-jul-2014 18:27:23 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * TiendaProducto generated by hbm2java
 */
@Entity
@Table(name="tienda_producto"
    ,catalog="teide2014"
)
@NamedQueries({
    @NamedQuery( name = "findByNombre",
     query = "from TiendaProducto tp where tp.nombre= :nombre"),
    @NamedQuery( name = "findByPrecio",
     query = "from TiendaProducto tp where tp.precio > :precio"),
    @NamedQuery( name = "findByExistencias",
     query = "from TiendaProducto tp where tp.existencias < 1")
})

public class TiendaProducto  implements java.io.Serializable {


     private Integer idProducto;
     private TiendaCategoria tiendaCategoria;
     private String nombre;
     private String descripcion;
     private String foto;
     private int existencias;
     private double precio;

    public TiendaProducto() {
    }

	
    public TiendaProducto(TiendaCategoria tiendaCategoria, String nombre, int existencias, double precio) {
        this.tiendaCategoria = tiendaCategoria;
        this.nombre = nombre;
        this.existencias = existencias;
        this.precio = precio;
    }
    public TiendaProducto(TiendaCategoria tiendaCategoria, String nombre, String descripcion, String foto, int existencias, double precio) {
       this.tiendaCategoria = tiendaCategoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.foto = foto;
       this.existencias = existencias;
       this.precio = precio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProducto", unique=true, nullable=false)
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCategoria", nullable=false)
    public TiendaCategoria getTiendaCategoria() {
        return this.tiendaCategoria;
    }
    
    public void setTiendaCategoria(TiendaCategoria tiendaCategoria) {
        this.tiendaCategoria = tiendaCategoria;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="foto", length=450)
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

    
    @Column(name="existencias", nullable=false)
    public int getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(int existencias) {
        this.existencias = existencias;
    }

    
    @Column(name="precio", nullable=false, precision=22, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }




}


