package modelo;
// Generated 10-jul-2014 15:21:40 by Hibernate Tools 3.6.0



/**
 * TiendaProducto generated by hbm2java
 */
public class TiendaProducto  implements java.io.Serializable {


     private Integer idProducto;
     private TiendaCategoria tiendaCategoria;
     private String nombre;
     private String descripcion;
     private String foto;
     private int existencias;
     private double precio;

    public TiendaProducto() {
    }

	
    public TiendaProducto(TiendaCategoria tiendaCategoria, String nombre, int existencias, double precio) {
        this.tiendaCategoria = tiendaCategoria;
        this.nombre = nombre;
        this.existencias = existencias;
        this.precio = precio;
    }
    public TiendaProducto(TiendaCategoria tiendaCategoria, String nombre, String descripcion, String foto, int existencias, double precio) {
       this.tiendaCategoria = tiendaCategoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.foto = foto;
       this.existencias = existencias;
       this.precio = precio;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public TiendaCategoria getTiendaCategoria() {
        return this.tiendaCategoria;
    }
    
    public void setTiendaCategoria(TiendaCategoria tiendaCategoria) {
        this.tiendaCategoria = tiendaCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public int getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(int existencias) {
        this.existencias = existencias;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }




}


